FROM golang:latest
MAINTAINER Chris Schmich <schmch@gmail.com>
COPY . /go/src/github.com/schmich/piriscope
WORKDIR /go/src/github.com/schmich/piriscope
CMD ["/bin/bash", "/go/src/github.com/schmich/piriscope/build-go.sh"]
